module(
    name = "cargo_env_examples",
    version = "0.0.0",
)

bazel_dep(name = "cargo_env.bzl")
local_path_override(
    module_name = "cargo_env.bzl",
    path = "../..",
)

# keep-sorted start
bazel_dep(name = "bazel_env.bzl", version = "0.7.2")
bazel_dep(name = "llvm", version = "0.8.3")
bazel_dep(name = "openssl", version = "3.5.5.bcr.4")
bazel_dep(name = "rules_rust", version = "0.70.0")
bazel_dep(name = "zstd", version = "1.5.7.bcr.1")
# keep-sorted end

register_toolchains("@llvm//toolchain:all")

rust = use_extension("@rules_rust//rust:extensions.bzl", "rust")
rust.toolchain(
    edition = "2024",
    rustfmt_version = "1.91.0",
    versions = ["1.91.0"],
)
use_repo(rust, "rust_toolchains")

crate = use_extension(
    "@rules_rust//crate_universe:extension.bzl",
    "crate",
)
crate.annotation_select(
    build_script_data = [
        "@openssl//:gen_dir",
    ],
    build_script_env = {"OPENSSL_DIR": "$(execpath @openssl//:gen_dir)"},
    crate = "openssl-sys",
    repositories = ["crates"],
    triples = [
        "x86_64-unknown-linux-gnu",
        "aarch64-unknown-linux-gnu",
    ],
)
crate.annotation(
    crate = "zstd-sys",
    gen_build_script = "off",
    repositories = ["crates"],
    deps = [
        "@zstd",
    ],
)
crate.from_cargo(
    cargo_lockfile = "//:Cargo.lock",
    manifests = [
        "//:Cargo.toml",
    ],
    supported_platform_triples = [
        "x86_64-unknown-linux-gnu",
        "aarch64-apple-darwin",
        "aarch64-unknown-linux-gnu",
    ],
)
use_repo(crate, "crates")

inject_repo(crate, "openssl", "zstd")
